### ISSUE TITLE
Upcoming breaking changes (v16)

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1248]
As we're nearing towards the official "beta" release of custom apps, we should probably take the chance to release a new major version with some of the things we would like to have included in the beta phase from the beginning.

Here are some of the things that come to my mind:
- [x] finally merge ~~#1008~~ #1269 
- [x] ~~remove static `Intl` exports from the dialog/modal pages components~~ #1283 
- [x] make `applicationName` a required field in `env.json` (this would be important for tracking usages during the beta phase) #1279 
- [x] finish and ship TS declarations (ref #589)
- [x] remove `MeasureFirstPaint` #1280 
- [x] remove ui component readmes and only keep mdx files. The readme then links to the docs page https://github.com/commercetools/merchant-center-application-kit/pull/1281/commits/e0d58ea93185ddd2153636ba545050011e70d6a5
- [x] change links to new website docs
- ???

**Comment by emmenko** [comment]
@jonnybel would you have time to pick up #1008 next week?

**Comment by jonnybel** [comment]
Yes, I can update it  👍

**Comment by tdeekens** [comment]
I have to think of some changes we might want to do to our permissions package. I am not sure it's even used by any custom app. Maybe also addition warnings and deprecation things first would be better than just going all mad on it.

**Comment by emmenko** [comment]
Yeah, whatever you might want to do add it to this list. I plan to release this within the next 2 weeks.

**Comment by emmenko** [comment]
@tdeekens can you think of anything we would need to include here regarding the custom apps tracking thing?

**Comment by tdeekens** [comment]
I commented somewhere else if you mean the differentiation between internal and external apps in logs?
