### ISSUE TITLE
Public beta launch checklist

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#1286]
- [x] redirect from appkit to new docs website are in place
- [x] announcement and/or release notes are ready and merged
- [x] update the MC UI to reflect the latest status
- [x] enable feature toggle for everyone
- [x] v16 release is finished and published
- [x] docs global links have the link to `/custom-applications`
- [x] docs website has search enabled
- [x] document uikit page
- [x] document caveats, appshell, test-utils and other missing pages
