### ISSUE TITLE
Upcoming breaking changes (v22)

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#3027]
```[tasklist]
### Tasks
- [ ] Migrate to Jest v29 https://github.com/commercetools/merchant-center-application-kit/pull/3026
- [ ] Migrate to FormatJS v6 and React Intl v6 https://github.com/commercetools/merchant-center-application-kit/pull/3029
- [ ] Remove Google Analytics tracking https://github.com/commercetools/merchant-center-application-kit/pull/3036
- [ ] Require min Node.js version to be v18 https://github.com/commercetools/merchant-center-application-kit/pull/3039
```
