### ISSUE TITLE
Static types

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#589]
**Is your feature request related to a problem? Please describe.**
Some of the packages (e.g. AppShell) have some pretty complex logic that often times causes small bugs to appear as it gets really tricky on finding out all the edge cases. This problem becomes more evident during refactorings.

**Describe the solution you'd like**
We should start adding static types to the application logic, with the goal of giving more confidence during refactorings and to also provide more helpful insights about the logic for new contributors.

**Additional context**
We can start with Flow, as it's more easy to integrate and we already use it in our backend services.

---

## Migration progress:

- [x] actions-global @emmenko #888 
- [x] application-components @emmenko  #921 
- [ ] application-shell (**this should be the last one to migrate**) @emmenko #1069 
- [x] application-shell-connectors @emmenko
- [x] assets (_not necessary_)
- [x] babel-preset-mc-app (_not necessary_)
- [x] browser-history @emmenko #885 
- [x] constants @emmenko
- [ ] create-mc-app
- [x] eslint-config-mc-app (_not necessary_)
- [x] i18n @emmenko #774 
- [x] jest-preset-mc-app (_not necessary_)
- [x] l10n @montezume #718 
- [ ] mc-dev-authentication
- [ ] mc-html-template
- [ ] mc-http-server
- [ ] mc-scripts
- [x] notifications @emmenko #884 
- [x] permissions @tdeekens #739 
- [x] react-notifications @emmenko #896 
- [x] sdk @emmenko #985
- [x] sentry @emmenko 
- [x] storage @montezume #715 
- [x] url-utils @montezume #717

**Comment by emmenko** [comment]
We decided to use TypeScript. From now on we will start migrating the packages to TS, step by step.

**Comment by tdeekens** [comment]
Migration status

- [x] sentry
- [x] storage
- [x] permissions
- [x] application-shell-connectors
- [x] url-utils
- [ ] actions-global
- [ ] application-shell
- [ ] sdk
- [ ] notifications

Please mark if you're working on a package with ⚠️ or add it :)

**Comment by montezume** [comment]
I just want to give some feedback from my side on the migration and my thoughts.

I did a few small simple packages, but when I got to more complex things, I realized that my knowledge of typescript is just not up to snuff. I don't have enough experience with it, or enough confidence with it, to migrate more packages. 

I also do not have time to both do my normal work, and learn TypeScript at the office. So something has to give, and for me, what gave was TypeScript. 

Has anyone else had this experience?

**Comment by tdeekens** [comment]
I would by far not consider myself an expert on TS. I've worked with it quite a bit (also weekends sadly) on flopflip. However, I still need to focus for migrating packages and can't do it on the side. If feel unsure/unsafe while using TypeScript we should maybe consider a workshop of sorts.

**Comment by montezume** [comment]
To be honest I'm not sure a workshop is enough (for me). I would need to spend 1-2 weeks working with TS fulltime, and this would need to be agreed upon with product I guess.

**Comment by emmenko** [comment]
I understand your argument and this was something we (I) expected. I'm also not a hardcore static typer but I guess I have gather a bit more experience in the past years.

I believe that in the long term the MC would greatly benefit from using static types, for several reasons. And therefore, I believe that we need to start getting the team familiar with working with static type systems. It's obviously an investment in terms of learning and development time, which would benefit both developers and the company itself.
This is also the main topic that I listed in the survey about our next frontend off-site.

We can/should discuss this in a proper fe-chapter meeting, but I definitely want to push this forward and I'm also willing on "teaching" and helping out as much as possible other devs in our team to "get up to speed".

**Comment by montezume** [comment]
I didn't want to put the topic on hold, or to reject the topic, only to start up a discussion about my feelings about my current TypeScript (and static types in general) knowledge. 

I found it especially important to share based on @tdeekens's feedback in this [PR](https://github.com/commercetools/merchant-center-application-kit/pull/801)

**Comment by adnasa** [comment]
Sorry for jumping late on the discussion, but I'm on the same boat 🙋🏽‍♀️

I'd love to be part of migrating our packages and get up to speed on TS. However I realised just rusty I am on this and get up to speed, I would need to spend some time on the weekend to catch up. I agree on @emmenko that is a field worthy of investment time, but this has to be aligned with product.

I've considered about attending a workshop. An option would be that we host an internal on our on, which would be much more appealing. In that case we could smash two flies on one stone. At the moment, I'm unsure if we need to discuss this further on an off site since we already agreed to take this path (unless I missed something).

**Comment by adnasa** [comment]
btw, to be absolutely clear. I am not saying that a workshop would be enough, this is a learning curve after all and a continuous process. And lastly to spend time on migrating packages will require alignment with product. I've already communicated this to my PO.

**Comment by emmenko** [comment]
> we already agreed to take this path

This was specifically for the appkit packages first. I mentioned the off-site to push it forward to not only the appkit, but especially the mc apps.

> I would need to spend some time on the weekend to catch up

This shouldn't be the case, unless you want to (in which case you are free to do so of course). Working hours should also be used for "training" and learning purposes. That's what I meant with _I'm also willing on "teaching" and helping out as much as possible other devs in our team to "get up to speed"_.

I think starting with some internal workshops would definitely be a good starting point!

**Comment by emmenko** [comment]
We can finally close this for now. All the UI packages have been migrated to TypeScript! 🎉
