### ISSUE TITLE
Upcoming breaking changes (v14)

### ISSUE THREAD

**Issue by emmenko** [commercetools/merchant-center-application-kit#748]
In the next major release I would like to go with first support for hooks, which will help us to ship less and more performant code.
Therefore, we should:
- support only react `>16.8.0`
- use hooks in the appkit packages implementations, easier to type as well
- I would also like to drop the HOC functions

We can maybe do the same in the upcoming uikit v10 and release both versions together.

Also maybe upgrade RTL.

Thoughts?

---
- [x] peer dependency react `>16.8` #795 
- [x] peer dependency react-redux `>7` #853 
- [ ] ~~(_check if it's worth it, otherwise deprecate it for now_) remove HOCs~~
- [x] (_optional_) use hooks in all appkit packages
- [x] (_optional_) use hooks for notifications #855 
- [x] (_optional_) use hooks for redux #852
- [x] (_optional_) use hooks for l10n #860 
- [x] (_optional_) upgrade to react-intl [v3](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md) #799 #817 
- [ ] ~~(_optional_) upgrade to react-apollo~~ [v3](https://github.com/apollographql/react-apollo/tree/master/packages/hooks) #801
- [x] (_check the effort_) upgrade to latest RTL -> `@testing-library/react` #811 
- [x] upgrade ct enzyme-extensions dep in jest to latest (for the `renderProp`) #796 
- [x] (_optional_) rename assets files #834
- [x] peer dependency uikit `>10` #825
- [x] migrate uikit v10 breaking changes #825
- [x] remove IE11 specific polyfills and ponyfills #830
- [x] stop transpiling for IE 11 #836
- [x] remove vendorsToTranspile webpack option #829 
- [x] update `permissions` constants to match new permissions (e.g. `ManageProject` has been removed) #815 
- [x] deprecate `storage` package #828 
- [x] remove deprecated components: `ServicePageResponseLayout` #828

**Comment by tdeekens** [comment]
I like it. Hope that people will update. However, I feel there are other reasons than bumping react why some projects do not get updated. To be fair, I don‘t think hooks for hocs will show meaningful performance improvements. It will make code easier to type and read for sure.

**Comment by emmenko** [comment]
Yeah, for the performance I mean more from the React side of things. For example less wrapping components, probably react can even further optimize things internally (just a hunch from my side).
Also Babel will generate less code 🙌

**Comment by montezume** [comment]
I would like to remove all of the usages HOCs from UI-Kit. `withMouseOver` etc can be done with pure css instead of using JavaScript.

**Comment by montezume** [comment]
Can we also make sure we include the assets renaming?

https://github.com/commercetools/merchant-center-application-kit/issues/546

🙏

**Comment by emmenko** [comment]
Short update: I've been trying to migrate the `notifications` package to TS and typing redux middlewares is kind of a nightmare.
That led me to consider refactoring the package to use hooks (including redux hooks), which makes it also easier to type.
Therefore, I would like to include those changes in this new release, or at least from this release onwards.

**Comment by emmenko** [comment]
Short update: I tried to use react apollo hooks (#801), which are supported by the upcoming react-apollo v3 (currently in _beta_). This lead to having to update react to 16.9 (currently in _alpha_) and RTL to latest (_@testing-library/react_).
Upgrading those dependencies require some extra work. We also need to coordinate how we should migrate the mc-fe apps to those versions.

We might decide to skip those updates in the v14 release but we will eventually need to do that in a next major (for instance, uikit should do the same).

**Comment by montezume** [comment]
Hm, UI-Kit already uses the latest @testing-library/react, and it doesn't use apollo. 😕

**Comment by emmenko** [comment]
Ah ok...it's also react to be updated...but anyway, as long as we keep in sync it should not matter

**Comment by tdeekens** [comment]
I am being a bit pungent again. Should we finish the static typing story and then move on to this. Sometimes I feel we just jump onto whatever we feel would be most fun or interesting _but also beneficial_. However, we should put ourselves to the same standards and ideals we communicate towards others: finish before starting.

**Comment by montezume** [comment]
@tdeekens by `this` are you referring to updating mc-fe to latest RTL, or are you referring to releasing a major app kit release?

**Comment by tdeekens** [comment]
Sorry, for releasing a major version of app-kit. I am all for planning it and thinking about it. Still, I wonder why we start it before we finish the static typing story. In all splitting and jumping between those "projects" just diffuses energy and effort and increases the likihood of leaving either or in a have finished state.

**Comment by montezume** [comment]
Well, we need a major version of app kit to update UI-Kit though, and we have spent a lot of energy preparing for the next major UI-Kit...

**Comment by montezume** [comment]
I understand your concerns about starting new things and not finishing, but we can't suffer from release paralysis. Sometimes we need to release breaking changes, and some of the time it's not even coming from the developers side, but from the designers, etc.

**Comment by tdeekens** [comment]
> Sometimes we need to release breaking changes, and some of the time it's not even coming from the developers side, but from the designers, etc.

It's not about breaking changes. It's about focusing in on something else started and finishing it. If this now became more important as UIKit depends on it, then that's a valid reason to not work on typing more right now.

**Comment by emmenko** [comment]
The static typings was something we agreed on doing "on the side", as it's not a high priority task. The v14 release is more important to finish first, as it brings more direct benefits.

With that in mind, in general start finishing before starting still stands of course!

**Comment by montezume** [comment]
We can also progressively (on the side if you will) migrate App Kit to hooks once the breaking change is released requiring React 16.8. 😄

**Comment by emmenko** [comment]
Should we include latest RTL in this release? I don't think we can really upgrade the mc-fe separately, as the app-shell test-utils rely on a specific rtl version.
